// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gphmcbniijsoplnfifgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwaG1jYm5paWpzb3BsbmZpZmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTkxMzYsImV4cCI6MjA3MTc5NTEzNn0.8u2DuL_Ykmm26Tm429Ih_H0U_HELL-LY614BUzBlkE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});